//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCredOnline.BNIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductProgram()
        {
            this.ProductProgramCheckList = new HashSet<ProductProgramCheckList>();
        }
    
        public long ProductID { get; set; }
        public string Libelle { get; set; }
        public Nullable<double> Taux { get; set; }
        public Nullable<double> Duree { get; set; }
        public Nullable<double> Frais { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Commentaires { get; set; }
        public string TypeDemande { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductProgramCheckList> ProductProgramCheckList { get; set; }
    }
}
