//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCredOnline.BNIData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long RequestID { get; set; }
        public string Ref_req { get; set; }
        public string CreditObjet { get; set; }
        public Nullable<int> CreditMontant { get; set; }
        public Nullable<double> CreditTaux { get; set; }
        public Nullable<long> CreditProgramID { get; set; }
        public string CreditProgram { get; set; }
        public Nullable<byte> DemandeEtat { get; set; }
        public Nullable<System.DateTime> DemandeDate { get; set; }
        public string AccountRacine { get; set; }
        public Nullable<int> CreditDuree { get; set; }
        public Nullable<long> PersonID { get; set; }
        public Nullable<byte> SyncStatut { get; set; }
        public Nullable<byte> CreditPeriodicite { get; set; }
        public string Reference { get; set; }
        public string SPItemID { get; set; }
        public string DemandeDossier { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> CreditMontantAvance { get; set; }
        public Nullable<int> CreditMontantEcheance { get; set; }
        public string CreditMontantLettre { get; set; }
        public Nullable<int> CreditQuotite { get; set; }
    }
}
