//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCredOnline.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Request = new HashSet<Request>();
        }
    
        public long PersonID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string AccountRacine { get; set; }
        public string Sexe { get; set; }
        public string Civilite { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string LieuNaissance { get; set; }
        public Nullable<int> PieceTypeID { get; set; }
        public string PieceNumero { get; set; }
        public Nullable<System.DateTime> PieceDateEtablissement { get; set; }
        public Nullable<System.DateTime> PieceDateExpiration { get; set; }
        public string HomePhone { get; set; }
        public string OfficePhone { get; set; }
        public string CellPhone { get; set; }
        public string AddressVille { get; set; }
        public string AddressQuartier { get; set; }
        public string AddressLot { get; set; }
        public Nullable<int> RegimeMatrimonialID { get; set; }
        public string ConjointNom { get; set; }
        public string ConjointPrenom { get; set; }
        public string ConjointDomicil { get; set; }
        public string ConjointPhone { get; set; }
        public string EmployeurNom { get; set; }
        public Nullable<int> EmployeurContratID { get; set; }
        public Nullable<System.DateTime> EmployeurDateEmbauche { get; set; }
        public string Profession { get; set; }
        public string EmployeurAdrPost { get; set; }
        public string EmployeurAdrGeo { get; set; }
        public string EmployeurPhone { get; set; }
        public Nullable<int> Salaire { get; set; }
        public Nullable<int> RevenuLocatif { get; set; }
        public Nullable<int> RevenuAgricole { get; set; }
        public Nullable<int> RevenuAutre { get; set; }
        public Nullable<int> RevenuTotal { get; set; }
        public Nullable<System.DateTime> EmployeurDateFinContrat { get; set; }
        public Nullable<int> NbEnfant { get; set; }
        public string EmployeurFonction { get; set; }
        public string EmployeurMatricule { get; set; }
        public string EmployeurProfession { get; set; }
        public string EmployeurCrade { get; set; }
        public string EmployeurNbAnneeExiste { get; set; }
        public Nullable<bool> EmployeurEstAgree { get; set; }
        public string EmployeurSegment { get; set; }
        public Nullable<bool> EstExploitantAgricole { get; set; }
        public string Nationalite { get; set; }
        public Nullable<System.DateTime> DateCompte { get; set; }
        public Nullable<bool> AcompteEpargne { get; set; }
    
        public virtual EmployeurContrat EmployeurContrat { get; set; }
        public virtual PieceType PieceType { get; set; }
        public virtual RegimeMatrimonial RegimeMatrimonial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
