//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCredOnline.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntreprisesAgrees
    {
        public long EntrepriseID { get; set; }
        public string RaisonSociale { get; set; }
        public string Telephone { get; set; }
        public string AdressePostale { get; set; }
        public string AdresseGeographique { get; set; }
        public Nullable<int> IndicatifID { get; set; }
    }
}
