//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCredOnline.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fichier
    {
        public long FileID { get; set; }
        public Nullable<long> RequestID { get; set; }
        public string Path { get; set; }
        public Nullable<byte> SyncStatut { get; set; }
        public string OnlineUrl { get; set; }
        public Nullable<long> CheckListID { get; set; }
        public byte[] File_Data { get; set; }
        public string File_MimeType { get; set; }
        public string File_Name { get; set; }
        public Nullable<int> File_Size { get; set; }
    
        public virtual ProductProgramCheckList ProductProgramCheckList { get; set; }
        public virtual Request Request { get; set; }
    }
}
