//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestCredOnline.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospects
    {
        public long ID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string AccountRacine { get; set; }
        public string Civilite { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public Nullable<int> PieceTypeID { get; set; }
        public string PieceNumero { get; set; }
        public Nullable<System.DateTime> PieceDateEtablissement { get; set; }
        public Nullable<System.DateTime> PieceDateExpiration { get; set; }
        public string CellPhone { get; set; }
        public Nullable<int> RegimeMatrimonialID { get; set; }
        public Nullable<int> EmployeurContratID { get; set; }
        public Nullable<System.DateTime> EmployeurDateEmbauche { get; set; }
        public Nullable<int> Salaire { get; set; }
        public Nullable<int> RevenuLocatif { get; set; }
        public Nullable<int> RevenuAgricole { get; set; }
        public Nullable<int> RevenuAutre { get; set; }
        public Nullable<int> RevenuTotal { get; set; }
        public Nullable<System.DateTime> EmployeurDateFinContrat { get; set; }
        public string Nationalite { get; set; }
        public Nullable<int> CreditMontant { get; set; }
        public Nullable<double> CreditTaux { get; set; }
        public Nullable<long> CreditProgramID { get; set; }
        public string CreditProgram { get; set; }
        public Nullable<int> CreditDuree { get; set; }
        public Nullable<byte> CreditPeriodicite { get; set; }
        public Nullable<int> CreditMontantAvance { get; set; }
        public Nullable<int> CreditMontantEcheance { get; set; }
        public Nullable<double> CreditQuotite { get; set; }
        public Nullable<double> CreditTauxEndettement { get; set; }
        public Nullable<System.DateTime> CreditDatePremVersement { get; set; }
    }
}
